# deploy/docker-compose.yml

version: '3.8'

services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    # allocate as many volumes as necessary, if needed.
    volumes:
      - ../storage/app:/var/www/html/storage/app
    environment:
      APP_NAME: Pusdiklat-Room
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY:
      APP_URL:
      DB_CONNECTION: mysql
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE:
      DB_USERNAME: nayor
      DB_PASSWORD: anjaymabar313
    #   DB_SOCKET: /cloudsql/refined-algebra-447708:asia-southeast2:ngekos-db-instance
      MAIL_MAILER: log
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    ports:
      - "8080:8080"
    networks:
      - n-laravel
    depends_on:
      - database

  database:
    restart: unless-stopped
    image: mariadb:lts-jammy
    volumes:
      - v-database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - n-laravel

volumes:
  v-database:


networks:
  n-laravel:
    driver: bridge
